WIP. pj-18-create-post, do w/o tests
acman/py_june pull request #5
Opened 2023-12-30 10:56 UTC by NykoEugen

2023-12-30 11:50 UTC, acman requested changes
Overall looks good! User logined check should be updated

2023-12-30 11:50 UTC, acman commented on posts/decorator.py
> +def user_required(view_func):
it is implemented in django, so there is no reason to write custom one

2023-12-30 11:50 UTC, acman commented on posts/views.py
> +class CreatePostView(View):
method decorator works only for methods
there is a good place to use `LoginRequiredMixin`, I think it has everything u need
```suggestion
class CreatePostView(LoginRequiredMixin, View):
```

2024-01-03 18:55 UTC, acman requested changes
some invalid tests

2024-01-03 18:55 UTC, acman commented on posts/tests.py
> +        )
suppose first url should get post

2024-01-03 18:55 UTC, acman commented on posts/tests.py
> +        )
get - should render PostForm
post - create Post

2024-01-04 13:05 UTC, acman requested changes

2024-01-04 13:05 UTC, acman commented on posts/tests.py
> +        )
I see, it is valid but it is not clear that self.create_view_url_get and self.create_view_url_post have the same url. So better to have only one consistent
```suggestion
        self.create_view_url = reverse(
            "posts:create", kwargs={"category_id": self.category.pk}
        )
```

2024-01-04 13:11 UTC, NykoEugen commented on posts/tests.py
> +        )
Oh, I see it, but don't pay attention.

2024-01-04 15:31 UTC, acman approved these changes
👍

2024-01-04 15:32 UTC, merged